(function(){
/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var rb="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
(function(){function k(){var a=this;this.s={};this.g=document.documentElement;var b=new Aa;b.rules=[];this.h=u.set(this.g,new u(b));this.i=!1;this.b=this.a=null;sb(function(){a.c()})}function L(){this.customStyles=[];this.enqueued=!1}function tb(){}function ja(a){this.cache={};this.c=void 0===a?100:a}function n(){}function u(a,b,c,d,e){this.G=a||null;this.b=b||null;this.Aa=c||[];this.P=null;this.Z=e||"";this.a=this.D=this.I=null}function p(){}function Aa(){this.end=this.start=0;this.rules=this.parent=
this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}function Zc(a){function b(b,c){Object.defineProperty(b,"innerHTML",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(b){var d=this,e=void 0;m(this)&&(e=[],Q(this,function(a){a!==d&&e.push(a)}));c.set.call(this,b);if(e)for(var f=0;f<e.length;f++){var g=e[f];1===g.__CE_state&&a.disconnectedCallback(g)}this.ownerDocument.__CE_hasRegistry?a.c(this):a.j(this);
return b}})}function c(b,c){v(b,"insertAdjacentElement",function(b,d){var e=m(d);b=c.call(this,b,d);e&&a.a(d);m(b)&&a.b(d);return b})}ub?v(Element.prototype,"attachShadow",function(a){return this.__CE_shadowRoot=a=ub.call(this,a)}):console.warn("Custom Elements: `Element#attachShadow` was not patched.");if(Ba&&Ba.get)b(Element.prototype,Ba);else if(Ca&&Ca.get)b(HTMLElement.prototype,Ca);else{var d=Da.call(document,"div");a.u(function(a){b(a,{enumerable:!0,configurable:!0,get:function(){return vb.call(this,
!0).innerHTML},set:function(a){var b="template"===this.localName?this.content:this;for(d.innerHTML=a;0<b.childNodes.length;)Ea.call(b,b.childNodes[0]);for(;0<d.childNodes.length;)ka.call(b,d.childNodes[0])}})})}v(Element.prototype,"setAttribute",function(b,c){if(1!==this.__CE_state)return wb.call(this,b,c);var d=Fa.call(this,b);wb.call(this,b,c);c=Fa.call(this,b);a.attributeChangedCallback(this,b,d,c,null)});v(Element.prototype,"setAttributeNS",function(b,c,d){if(1!==this.__CE_state)return xb.call(this,
b,c,d);var e=la.call(this,b,c);xb.call(this,b,c,d);d=la.call(this,b,c);a.attributeChangedCallback(this,c,e,d,b)});v(Element.prototype,"removeAttribute",function(b){if(1!==this.__CE_state)return yb.call(this,b);var c=Fa.call(this,b);yb.call(this,b);null!==c&&a.attributeChangedCallback(this,b,c,null,null)});v(Element.prototype,"removeAttributeNS",function(b,c){if(1!==this.__CE_state)return zb.call(this,b,c);var d=la.call(this,b,c);zb.call(this,b,c);var e=la.call(this,b,c);d!==e&&a.attributeChangedCallback(this,
c,d,e,b)});Ab?c(HTMLElement.prototype,Ab):Bb?c(Element.prototype,Bb):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");Cb(a,Element.prototype,{Ra:$c,append:ad});bd(a,{nb:cd,mb:dd,xb:ed,remove:fd})}function bd(a,b){var c=Element.prototype;c.before=function(c){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&m(a)});b.nb.apply(this,d);for(var g=0;g<f.length;g++)a.a(f[g]);if(m(this))for(f=0;f<d.length;f++)g=d[f],
g instanceof Element&&a.b(g)};c.after=function(c){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&m(a)});b.mb.apply(this,d);for(var g=0;g<f.length;g++)a.a(f[g]);if(m(this))for(f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.b(g)};c.replaceWith=function(c){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];var f=d.filter(function(a){return a instanceof Node&&m(a)}),g=m(this);b.xb.apply(this,d);for(var h=0;h<f.length;h++)a.a(f[h]);
if(g)for(a.a(this),f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.b(g)};c.remove=function(){var c=m(this);b.remove.call(this);c&&a.a(this)}}function gd(a){function b(b,d){Object.defineProperty(b,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(b){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,b);else{var c=void 0;if(this.firstChild){var e=this.childNodes,h=e.length;if(0<h&&m(this))for(var c=Array(h),l=0;l<h;l++)c[l]=e[l]}d.set.call(this,b);if(c)for(b=0;b<c.length;b++)a.a(c[b])}}})}
v(Node.prototype,"insertBefore",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=Db.call(this,b,d);if(m(this))for(d=0;d<c.length;d++)a.b(c[d]);return b}c=m(b);d=Db.call(this,b,d);c&&a.a(b);m(this)&&a.b(b);return d});v(Node.prototype,"appendChild",function(b){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=ka.call(this,b);if(m(this))for(var e=0;e<c.length;e++)a.b(c[e]);return b}c=m(b);e=ka.call(this,b);c&&a.a(b);m(this)&&
a.b(b);return e});v(Node.prototype,"cloneNode",function(b){b=vb.call(this,b);this.ownerDocument.__CE_hasRegistry?a.c(b):a.j(b);return b});v(Node.prototype,"removeChild",function(b){var c=m(b),e=Ea.call(this,b);c&&a.a(b);return e});v(Node.prototype,"replaceChild",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=Eb.call(this,b,d);if(m(this))for(a.a(d),d=0;d<c.length;d++)a.b(c[d]);return b}var c=m(b),f=Eb.call(this,b,d),g=m(this);g&&a.a(d);c&&a.a(b);g&&
a.b(b);return f});Ga&&Ga.get?b(Node.prototype,Ga):a.u(function(a){b(a,{enumerable:!0,configurable:!0,get:function(){for(var a=[],b=0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)Ea.call(this,this.firstChild);ka.call(this,document.createTextNode(a))}})})}function hd(a){v(Document.prototype,"createElement",function(b){if(this.__CE_hasRegistry){var c=a.f(b);if(c)return new c.constructor}b=Da.call(this,b);a.g(b);return b});
v(Document.prototype,"importNode",function(b,c){b=id.call(this,b,c);this.__CE_hasRegistry?a.c(b):a.j(b);return b});v(Document.prototype,"createElementNS",function(b,c){if(this.__CE_hasRegistry&&(null===b||"http://www.w3.org/1999/xhtml"===b)){var d=a.f(c);if(d)return new d.constructor}b=jd.call(this,b,c);a.g(b);return b});Cb(a,Document.prototype,{Ra:kd,append:ld})}function Cb(a,b,c){b.prepend=function(b){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof
Node&&m(a)});c.Ra.apply(this,d);for(var g=0;g<f.length;g++)a.a(f[g]);if(m(this))for(f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.b(g)};b.append=function(b){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&m(a)});c.append.apply(this,d);for(var g=0;g<f.length;g++)a.a(f[g]);if(m(this))for(f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.b(g)}}function md(a){window.HTMLElement=function(){function b(){var b=this.constructor,d=a.J(b);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");
var e=d.constructionStack;if(!e.length)return e=Da.call(document,d.localName),Object.setPrototypeOf(e,b.prototype),e.__CE_state=1,e.__CE_definition=d,a.g(e),e;var d=e.length-1,f=e[d];if(f===Fb)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");e[d]=Fb;Object.setPrototypeOf(f,b.prototype);a.g(f);return f}b.prototype=nd.prototype;return b}()}function r(a){this.f=!1;this.a=a;this.h=new Map;this.g=function(a){return a()};this.b=!1;this.c=
[];this.i=new Ha(a,document)}function Gb(){var a=this;this.b=this.a=void 0;this.c=new Promise(function(b){a.b=b;a.a&&b(a.a)})}function Ha(a,b){this.b=a;this.a=b;this.L=void 0;this.b.c(this.a);"loading"===this.a.readyState&&(this.L=new MutationObserver(this.f.bind(this)),this.L.observe(this.a,{childList:!0,subtree:!0}))}function z(){this.s=new Map;this.o=new Map;this.i=[];this.h=!1}function q(a,b){if(a!==Hb)throw new TypeError("Illegal constructor");a=document.createDocumentFragment();a.__proto__=
q.prototype;a.i(b);return a}function H(a){this.root=a;this.ea="slot"}function V(a){if(!a.__shady||void 0===a.__shady.firstChild){a.__shady=a.__shady||{};a.__shady.firstChild=Ia(a);a.__shady.lastChild=Ja(a);Ib(a);for(var b=a.__shady.childNodes=da(a),c=0,d;c<b.length&&(d=b[c]);c++)d.__shady=d.__shady||{},d.__shady.parentNode=a,d.__shady.nextSibling=b[c+1]||null,d.__shady.previousSibling=b[c-1]||null,Jb(d)}}function od(a){var b=a&&a.L;b&&(b.da.delete(a.gb),b.da.size||(a.kb.__shady.X=null))}function pd(a,
b){a.__shady=a.__shady||{};a.__shady.X||(a.__shady.X=new ma);a.__shady.X.da.add(b);var c=a.__shady.X;return{gb:b,L:c,kb:a,takeRecords:function(){return c.takeRecords()}}}function ma(){this.a=!1;this.addedNodes=[];this.removedNodes=[];this.da=new Set}function C(a){return"ShadyRoot"===a.cb}function W(a){a=a.getRootNode();if(C(a))return a}function Ka(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e;d<c.length&&(e=c[d]);d++){var f=Object.getOwnPropertyDescriptor(b,e);f&&Object.defineProperty(a,
e,f)}}function La(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)Ka(a,c[d]);return a}function qd(a,b){for(var c in b)a[c]=b[c]}function Kb(a){Ma.push(a);Na.textContent=Lb++}function Mb(a){Oa||(Oa=!0,Kb(na));ea.push(a)}function na(){Oa=!1;for(var a=!!ea.length;ea.length;)ea.shift()();return a}function rd(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===
a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})}function Nb(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Ob(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}function Pa(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g;e<f&&(g=d[e]);e++){var h;
a:{var l;h=g;l=a;var B=b;switch(h.nodeType){case Node.ELEMENT_NODE:for(var k=h.localName,G="<"+k,m=h.attributes,n=0;l=m[n];n++)G+=" "+l.name+'="'+l.value.replace(sd,Nb)+'"';G+=">";h=td[k]?G:G+Pa(h,B)+"</"+k+">";break a;case Node.TEXT_NODE:h=h.data;h=l&&ud[l.localName]?h:h.replace(vd,Nb);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),Error("not implemented");}}c+=h}return c}function R(a){D.currentNode=a;return D.parentNode()}function Ia(a){D.currentNode=
a;return D.firstChild()}function Ja(a){D.currentNode=a;return D.lastChild()}function Pb(a){D.currentNode=a;return D.previousSibling()}function Qb(a){D.currentNode=a;return D.nextSibling()}function da(a){var b=[];D.currentNode=a;for(a=D.firstChild();a;)b.push(a),a=D.nextSibling();return b}function Rb(a){E.currentNode=a;return E.parentNode()}function Sb(a){E.currentNode=a;return E.firstChild()}function Tb(a){E.currentNode=a;return E.lastChild()}function Ub(a){E.currentNode=a;return E.previousSibling()}
function Vb(a){E.currentNode=a;return E.nextSibling()}function Wb(a){var b=[];E.currentNode=a;for(a=E.firstChild();a;)b.push(a),a=E.nextSibling();return b}function Xb(a){return Pa(a,function(a){return da(a)})}function Yb(a){if(a.nodeType!==Node.ELEMENT_NODE)return a.nodeValue;a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b}function M(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,
d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function S(a){M(a,Zb);M(a,Qa);M(a,Ra)}function $b(a,b,c){Jb(a);c=c||null;a.__shady=a.__shady||{};b.__shady=b.__shady||{};c&&(c.__shady=c.__shady||{});a.__shady.previousSibling=c?c.__shady.previousSibling:b.lastChild;var d=a.__shady.previousSibling;d&&d.__shady&&(d.__shady.nextSibling=a);(d=a.__shady.nextSibling=c)&&d.__shady&&(d.__shady.previousSibling=a);a.__shady.parentNode=b;c?c===b.__shady.firstChild&&(b.__shady.firstChild=a):(b.__shady.lastChild=
a,b.__shady.firstChild||(b.__shady.firstChild=a));b.__shady.childNodes=null}function ac(a){var b=a.__shady&&a.__shady.parentNode,c,d=W(a);if(b||d){c=bc(a);if(b){a.__shady=a.__shady||{};b.__shady=b.__shady||{};a===b.__shady.firstChild&&(b.__shady.firstChild=a.__shady.nextSibling);a===b.__shady.lastChild&&(b.__shady.lastChild=a.__shady.previousSibling);var e=a.__shady.previousSibling,f=a.__shady.nextSibling;e&&(e.__shady=e.__shady||{},e.__shady.nextSibling=f);f&&(f.__shady=f.__shady||{},f.__shady.previousSibling=
e);a.__shady.parentNode=a.__shady.previousSibling=a.__shady.nextSibling=void 0;void 0!==b.__shady.childNodes&&(b.__shady.childNodes=null)}if(e=d){for(var g,e=d.sa(),f=0;f<e.length;f++){var h=e[f],l;a:{for(l=h;l;){if(l==a){l=!0;break a}l=l.parentNode}l=void 0}if(l)for(h=h.assignedNodes({flatten:!0}),l=0;l<h.length;l++){g=!0;var B=h[l],k=R(B);k&&X.call(k,B)}}e=g}b=b&&d&&b.localName===d.B.ea;if(e||b)d.ba=!1,oa(d)}Sa(a);return c}function Ta(a,b,c){if(a=a.__shady&&a.__shady.X)b&&a.addedNodes.push(b),c&&
a.removedNodes.push(c),a.zb()}function Ua(a){if(a&&a.nodeType){a.__shady=a.__shady||{};var b=a.__shady.Ba;void 0===b&&(C(a)?b=a:b=(b=a.parentNode)?Ua(b):a,document.documentElement.contains(a)&&(a.__shady.Ba=b));return b}}function cc(a,b,c){var d,e=c.B.ea;if(a.nodeType!==Node.DOCUMENT_FRAGMENT_NODE||a.__noInsertionPoint)a.localName===e&&(V(b),V(a),d=!0);else for(var e=a.querySelectorAll(e),f=0,g,h;f<e.length&&(g=e[f]);f++)h=g.parentNode,h===a&&(h=b),h=cc(g,h,c),d=d||h;return d}function dc(a){return(a=
a&&a.__shady&&a.__shady.root)&&a.ya()}function Sa(a){if(a.__shady&&void 0!==a.__shady.Ba)for(var b=a.childNodes,c=0,d=b.length,e;c<d&&(e=b[c]);c++)Sa(e);a.__shady=a.__shady||{};a.__shady.Ba=void 0}function bc(a){a=a.parentNode;if(dc(a))return oa(a.__shady.root),!0}function oa(a){a.ra=!0;a.update()}function ec(a,b){"slot"===b?bc(a):"slot"===a.localName&&"name"===b&&(a=W(a))&&a.update()}function pa(a,b,c){var d=[];fc(a.childNodes,b,c,d);return d}function fc(a,b,c,d){for(var e=0,f=a.length,g;e<f&&(g=
a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var l=b,B=c,k=d,G=l(h);G&&k.push(h);B&&B(G)?h=G:(fc(h.childNodes,l,B,k),h=void 0)}if(h)break}}function gc(a){a=a.getRootNode();C(a)&&a.Sa()}function hc(a,b,c){if(c){var d=c.__shady&&c.__shady.parentNode;if(void 0!==d&&d!==a||void 0===d&&R(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;b.nodeType!==Node.DOCUMENT_FRAGMENT_NODE&&
((d=b.__shady&&b.__shady.parentNode)?(Ta(d,null,b),ac(b)):(b.parentNode&&X.call(b.parentNode,b),Sa(b)));var d=c,e=W(a),f;e&&(b.__noInsertionPoint&&!e.ra&&(e.ba=!0),f=cc(b,a,e))&&(e.ba=!1);if(a.__shady&&void 0!==a.__shady.firstChild)if(Ib(a),a.__shady=a.__shady||{},void 0!==a.__shady.firstChild&&(a.__shady.childNodes=null),b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){for(var g=b.childNodes,h=0;h<g.length;h++)$b(g[h],a,d);b.__shady=b.__shady||{};g=void 0!==b.__shady.firstChild?null:void 0;b.__shady.firstChild=
b.__shady.lastChild=g;b.__shady.childNodes=g}else $b(b,a,d);var g=f,h=e&&e.B.ea||"",l=b.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&!b.__noInsertionPoint&&h&&b.querySelector(h);f=l&&l.parentNode.nodeType!==Node.DOCUMENT_FRAGMENT_NODE;((l=l||b.localName===h)||a.localName===h||g)&&e&&oa(e);(e=dc(a))&&oa(a.__shady&&a.__shady.root);if(!(e||l&&!f||a.__shady.root||d&&C(d.parentNode)&&d.parentNode.M)){if(c&&(d=W(c))){var B;if(c.localName===d.B.ea)a:{d=c.assignedNodes({flatten:!0});e=Ua(c);f=0;for(g=d.length;f<
g&&(B=d[f]);f++)if(e.fa(c,B))break a;B=void 0}else B=c;c=B}B=C(a)?a.host:a;c?Va.call(B,b,c):ic.call(B,b)}Ta(a,b);return b}function jc(a,b){if(a.ownerDocument!==document)return Wa.call(document,a,b);var c=Wa.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=jc(a[b],!0),c.appendChild(d)}return c}function Xa(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;
c[c.length-1]===document&&c.push(window);return c}function kc(a,b){if(!C)return a;a=Xa(a,!0);for(var c=0,d,e,f,g;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(g=a.indexOf(f),e=f),!C(f)||-1<g)return d}function Ya(a){function b(b,d){b=new a(b,d);b.na=d&&!!d.composed;return b}qd(b,a);b.prototype=a.prototype;return b}function lc(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&a.target!==a.relatedTarget&&(e.call(b,a),!a.ab);d++);}function wd(a){var b=
a.composedPath(),c;Object.defineProperty(a,"currentTarget",{get:function(){return c},configurable:!0});for(var d=b.length-1;0<=d;d--)if(c=b[d],lc(a,c,"capture"),a.oa)return;Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});for(var e,d=0;d<b.length;d++)if(c=b[d],!d||c.shadowRoot&&c.shadowRoot===e)if(lc(a,c,"bubble"),c!==window&&(e=c.getRootNode()),a.oa)break}function mc(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],l=h.type,B=h.capture,k=h.once,G=h.passive;if(b===
h.node&&c===l&&d===B&&e===k&&f===G)return g}return-1}function nc(a,b,c){if(b){var d,e,f;"object"===typeof c?(d=!!c.capture,e=!!c.once,f=!!c.passive):(d=!!c,f=e=!1);var g=c&&c.pa||this,h=b.$;if(h){if(-1<mc(h,g,a,d,e,f))return}else b.$=[];h=function(d){e&&this.removeEventListener(a,b,c);d.__target||oc(d);var f;g!==this&&(f=Object.getOwnPropertyDescriptor(d,"currentTarget"),Object.defineProperty(d,"currentTarget",{get:function(){return g},configurable:!0}));if(d.composed||-1<d.composedPath().indexOf(g))if(d.target===
d.relatedTarget)d.eventPhase===Event.BUBBLING_PHASE&&d.stopImmediatePropagation();else if(d.eventPhase===Event.CAPTURING_PHASE||d.bubbles||d.target===g){var h="object"===typeof b&&b.handleEvent?b.handleEvent(d):b.call(g,d);g!==this&&(f?(Object.defineProperty(d,"currentTarget",f),f=null):delete d.currentTarget);return h}};b.$.push({node:this,type:a,capture:d,once:e,passive:f,Cb:h});Za[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][d?
"capture":"bubble"].push(h)):(this instanceof Window?pc:qc).call(this,a,h,c)}}function rc(a,b,c){if(b){var d,e,f;"object"===typeof c?(d=!!c.capture,e=!!c.once,f=!!c.passive):(d=!!c,f=e=!1);var g=c&&c.pa||this,h=void 0,l;l=null;try{l=b.$}catch(B){}l&&(e=mc(l,g,a,d,e,f),-1<e&&(h=l.splice(e,1)[0].Cb,l.length||(b.$=void 0)));(this instanceof Window?sc:tc).call(this,a,h||b,c);h&&Za[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][d?"capture":"bubble"],h=a.indexOf(h),-1<h&&a.splice(h,1))}}
function xd(){for(var a in Za)window.addEventListener(a,function(a){a.__target||(oc(a),wd(a))},!0)}function oc(a){a.__target=a.target;a.Ha=a.relatedTarget;if(y.W){var b=uc,c=Object.getPrototypeOf(a);if(!c.hasOwnProperty("__patchProto")){var d=Object.create(c);d.Eb=c;Ka(d,b);c.__patchProto=d}a.__proto__=c.__patchProto}else Ka(a,uc)}function fa(a,b){return{index:a,Y:[],ca:b}}function yd(a,b,c,d){var e=0,f=0,g=0,h=0,l=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<l;g++)if(a[g]!==c[g])break a;g=l}if(b==
a.length&&d==c.length){for(var h=a.length,k=c.length,A=0;A<l-g&&zd(a[--h],c[--k]);)A++;h=A}e+=g;f+=g;b-=h;d-=h;if(!(b-e||d-f))return[];if(e==b){for(b=fa(e,0);f<d;)b.Y.push(c[f++]);return[b]}if(f==d)return[fa(e,b-e)];l=e;g=f;d=d-g+1;h=b-l+1;b=Array(d);for(k=0;k<d;k++)b[k]=Array(h),b[k][0]=k;for(k=0;k<h;k++)b[0][k]=k;for(k=1;k<d;k++)for(A=1;A<h;A++)if(a[l+A-1]===c[g+k-1])b[k][A]=b[k-1][A-1];else{var G=b[k-1][A]+1,m=b[k][A-1]+1;b[k][A]=G<m?G:m}l=b.length-1;g=b[0].length-1;d=b[l][g];for(a=[];0<l||0<g;)l?
g?(h=b[l-1][g-1],k=b[l-1][g],A=b[l][g-1],G=k<A?k<h?k:h:A<h?A:h,G==h?(h==d?a.push(0):(a.push(1),d=h),l--,g--):G==k?(a.push(3),l--,d=k):(a.push(2),g--,d=A)):(a.push(3),l--):(a.push(2),g--);a.reverse();b=void 0;l=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(l.push(b),b=void 0);e++;f++;break;case 1:b||(b=fa(e,0));b.ca++;e++;b.Y.push(c[f]);f++;break;case 2:b||(b=fa(e,0));b.ca++;e++;break;case 3:b||(b=fa(e,0)),b.Y.push(c[f]),f++}b&&l.push(b);return l}function zd(a,b){return a===b}function vc(a){gc(a);
return a.__shady&&a.__shady.assignedSlot||null}function J(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}}function Ad(){var a=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;J(window.Node.prototype,Bd);J(window.Window.prototype,Cd);J(window.Text.prototype,Dd);J(window.DocumentFragment.prototype,$a);J(window.Element.prototype,wc);J(window.Document.prototype,
xc);window.HTMLSlotElement&&J(window.HTMLSlotElement.prototype,yc);J(a.prototype,Ed);y.W&&(S(window.Node.prototype),S(window.Text.prototype),S(window.DocumentFragment.prototype),S(window.Element.prototype),S(a.prototype),S(window.Document.prototype),window.HTMLSlotElement&&S(window.HTMLSlotElement.prototype))}function zc(a){var b=Fd.has(a);a=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(a);return!b&&a}function m(a){var b=a.isConnected;if(void 0!==b)return b;for(;a&&!(a.__CE_isImportDocument||a instanceof
Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}function ab(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}function Q(a,b,c){c=c?c:new Set;for(var d=a;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;b(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)Q(d,
b,c);d=ab(a,e);continue}else if("template"===f){d=ab(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)Q(e,b,c)}d=d.firstChild?d.firstChild:ab(a,d)}}function v(a,b,c){a[b]=c}function bb(a){a=a.replace(N.pb,"").replace(N.port,"");var b=Ac,c=a,d=new Aa;d.start=0;d.end=c.length;for(var e=d,f=0,g=c.length;f<g;f++)if("{"===c[f]){e.rules||(e.rules=[]);var h=e,l=h.rules[h.rules.length-1]||null,e=new Aa;e.start=f+1;e.parent=h;e.previous=l;h.rules.push(e)}else"}"===c[f]&&(e.end=f+1,
e=e.parent||d);return b(d,a)}function Ac(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&((c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=Gd(c),c=c.replace(N.Qa," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=!c.indexOf("@"),a.atRule)?c.indexOf("@media")?c.match(N.vb)&&(a.type=I.ma,a.keyframesName=a.selector.split(N.Qa).pop()):a.type=I.MEDIA_RULE:a.type=c.indexOf("--")?I.STYLE_RULE:I.Da);if(c=a.rules)for(var d=
0,e=c.length,f;d<e&&(f=c[d]);d++)Ac(f,b);return a}function Gd(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}function Bc(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var g=e.length,h;f<g&&(h=e[f]);f++)d=Bc(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(N.La,"").replace(N.Pa,""),b=b.replace(N.wb,"").replace(N.Bb,"")),(d=b.trim())&&
(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}function Cc(a){w=a&&a.shimcssproperties?!1:t||!(navigator.userAgent.match("AppleWebKit/601")||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}function Y(a,b){if(!a)return"";"string"===typeof a&&(a=bb(a));b&&Z(a,b);return Bc(a,w)}function qa(a){!a.__cssRules&&a.textContent&&(a.__cssRules=bb(a.textContent));return a.__cssRules||null}function Dc(a){return!!a.parent&&a.parent.type===
I.ma}function Z(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===I.MEDIA_RULE){var g=a.selector.match(Hd);g&&(window.matchMedia(g[1]).matches||(e=!0))}f===I.STYLE_RULE?b(a):c&&f===I.ma?c(a):f===I.Da&&(e=!0);if((a=a.rules)&&!e)for(var e=0,f=a.length,h;e<f&&(h=a[e]);e++)Z(h,b,c,d)}}function cb(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;Ec(e,c,d);return e}function Ec(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);T?a.compareDocumentPosition(T)===
Node.DOCUMENT_POSITION_PRECEDING&&(T=a):T=a}function Fc(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d;a:{var e=0;d=c+3;for(var f=a.length;d<f;d++)if("("===a[d])e++;else if(")"===a[d]&&!--e)break a;d=-1}e=a.substring(c+4,d);c=a.substring(0,c);a=Fc(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function ra(a,b){t?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}function U(a){var b=
a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,Z:c}}function Gc(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode(),g;g=e;var h=[];g.classList?h=Array.from(g.classList):g instanceof window.SVGElement&&g.hasAttribute("class")&&(h=g.getAttribute("class").split(/\s+/));
g=h;h=g.indexOf(x.c);(g=-1<h?g[h+1]:"")&&f===e.ownerDocument?x.a(e,g,!0):f.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(f=f.host)&&(f=U(f).is,g!==f&&(g&&x.a(e,g,!0),x.a(e,f)))}}}}function Id(a){if(a=sa[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Hc(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Jd(a){a._applyShimValidatingVersion=a._applyShimNextVersion;
a.b||(a.b=!0,Kd.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a.b=!1}))}function sb(a){requestAnimationFrame(function(){Ic?Ic(a):(db||(db=new Promise(function(a){eb=a}),"complete"===document.readyState?eb():document.addEventListener("readystatechange",function(){"complete"===document.readyState&&eb()})),db.then(function(){a&&a()}))})}(function(){if(!function(){var a=document.createEvent("Event");a.initEvent("foo",!0,!0);a.preventDefault();return a.defaultPrevented}()){var a=Event.prototype.preventDefault;
Event.prototype.preventDefault=function(){this.cancelable&&(a.call(this),Object.defineProperty(this,"defaultPrevented",{get:function(){return!0},configurable:!0}))}}var b=/Trident/.test(navigator.userAgent);if(!window.CustomEvent||b&&"function"!==typeof window.CustomEvent)window.CustomEvent=function(a,b){b=b||{};var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c},window.CustomEvent.prototype=window.Event.prototype;if(!window.Event||b&&"function"!==
typeof window.Event){var c=window.Event;window.Event=function(a,b){b=b||{};var c=document.createEvent("Event");c.initEvent(a,!!b.bubbles,!!b.cancelable);return c};if(c)for(var d in c)window.Event[d]=c[d];window.Event.prototype=c.prototype}if(!window.MouseEvent||b&&"function"!==typeof window.MouseEvent){b=window.MouseEvent;window.MouseEvent=function(a,b){b=b||{};var c=document.createEvent("MouseEvent");c.initMouseEvent(a,!!b.bubbles,!!b.cancelable,b.view||window,b.detail,b.screenX,b.screenY,b.clientX,
b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);return c};if(b)for(d in b)window.MouseEvent[d]=b[d];window.MouseEvent.prototype=b.prototype}Array.from||(Array.from=function(a){return[].slice.call(a)});Object.assign||(Object.assign=function(a,b){for(var c=[].slice.call(arguments,1),d=0,e;d<c.length;d++)if(e=c[d])for(var f=a,k=e,m=Object.getOwnPropertyNames(k),n=0;n<m.length;n++)e=m[n],f[e]=k[e];return a})})(window.WebComponents);(function(){function a(){}var b="undefined"===
typeof HTMLTemplateElement;/Trident/.test(navigator.userAgent)&&function(){var a=Document.prototype.importNode;Document.prototype.importNode=function(){var b=a.apply(this,arguments);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){var c=this.createDocumentFragment();c.appendChild(b);return c}return b}}();var c=Node.prototype.cloneNode,d=Document.prototype.createElement,e=Document.prototype.importNode,f=function(){if(!b){var a=document.createElement("template"),c=document.createElement("template");c.content.appendChild(document.createElement("div"));
a.content.appendChild(c);a=a.cloneNode(!0);return 0===a.content.childNodes.length||0===a.content.firstChild.content.childNodes.length||!(document.createDocumentFragment().cloneNode()instanceof DocumentFragment)}}();if(b){var g=function(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case "\u00a0":return"&nbsp;"}},h=function(b){Object.defineProperty(b,"innerHTML",{get:function(){for(var a="",b=this.content.firstChild;b;b=b.nextSibling)a+=b.outerHTML||b.data.replace(q,
g);return a},set:function(b){l.body.innerHTML=b;for(a.b(l);this.content.firstChild;)this.content.removeChild(this.content.firstChild);for(;l.body.firstChild;)this.content.appendChild(l.body.firstChild)},configurable:!0})},l=document.implementation.createHTMLDocument("template"),k=!0,A=document.createElement("style");A.textContent="template{display:none;}";var m=document.head;m.insertBefore(A,m.firstElementChild);a.prototype=Object.create(HTMLElement.prototype);var n=!document.createElement("div").hasOwnProperty("innerHTML");
a.N=function(b){if(!b.content){b.content=l.createDocumentFragment();for(var c;c=b.firstChild;)b.content.appendChild(c);if(n)b.__proto__=a.prototype;else if(b.cloneNode=function(b){return a.a(this,b)},k)try{h(b)}catch(me){k=!1}a.b(b.content)}};h(a.prototype);a.b=function(b){b=b.querySelectorAll("template");for(var c=0,d=b.length,e;c<d&&(e=b[c]);c++)a.N(e)};document.addEventListener("DOMContentLoaded",function(){a.b(document)});Document.prototype.createElement=function(){var b=d.apply(this,arguments);
"template"===b.localName&&a.N(b);return b};var q=/[&\u00A0<>]/g}if(b||f)a.a=function(a,b){var d=c.call(a,!1);this.N&&this.N(d);b&&(d.content.appendChild(c.call(a.content,!0)),this.xa(d.content,a.content));return d},a.prototype.cloneNode=function(b){return a.a(this,b)},a.xa=function(a,b){if(b.querySelectorAll){b=b.querySelectorAll("template");a=a.querySelectorAll("template");for(var c=0,d=a.length,e,f;c<d;c++)f=b[c],e=a[c],this.N&&this.N(f),e.parentNode.replaceChild(f.cloneNode(!0),e)}},Node.prototype.cloneNode=
function(b){var d;if(this instanceof DocumentFragment)if(b)d=this.ownerDocument.importNode(this,!0);else return this.ownerDocument.createDocumentFragment();else d=c.call(this,b);b&&a.xa(d,this);return d},Document.prototype.importNode=function(b,c){if("template"===b.localName)return a.a(b,c);var d=e.call(this,b,c);c&&a.xa(d,b);return d},f&&(window.HTMLTemplateElement.prototype.cloneNode=function(b){return a.a(this,b)});b&&(window.HTMLTemplateElement=a)})();!function(a,b){"object"==typeof exports&&
"undefined"!=typeof module?module.exports=b():"function"==typeof define&&define.Hb?define(b):a.ES6Promise=b()}(window,function(){function a(a,b){C[aa]=a;C[aa+1]=b;aa+=2;2===aa&&(E?E(g):N())}function b(){return function(){return process.Kb(g)}}function c(){return"undefined"!=typeof D?function(){D(g)}:f()}function d(){var a=0,b=new L(g),c=document.createTextNode("");return b.observe(c,{characterData:!0}),function(){c.data=a=++a%2}}function e(){var a=new MessageChannel;return a.port1.onmessage=g,function(){return a.port2.postMessage(0)}}
function f(){var a=setTimeout;return function(){return a(g,1)}}function g(){for(var a=0;a<aa;a+=2)(0,C[a])(C[a+1]),C[a]=void 0,C[a+1]=void 0;aa=0}function h(){try{var a=require("vertx");return D=a.Mb||a.Lb,c()}catch(Jc){return f()}}function l(b,c){var d=arguments,e=this,f=new this.constructor(m);void 0===f[K]&&Kc(f);var g=e.m;return g?!function(){var b=d[g-1];a(function(){return ga(g,f,b,e.l)})}():v(e,f,b,c),f}function k(a){if(a&&"object"==typeof a&&a.constructor===this)return a;var b=new this(m);
return t(b,a),b}function m(){}function n(a){try{return a.then}catch(Jc){return P.error=Jc,P}}function q(a,b,c,d){try{a.call(b,c,d)}catch(Nd){return Nd}}function p(b,c,d){a(function(a){var b=!1,e=q(d,c,function(d){b||(b=!0,c!==d?t(a,d):r(a,d))},function(c){b||(b=!0,O(a,c))});!b&&e&&(b=!0,O(a,e))},b)}function u(a,b){b.m===M?r(a,b.l):b.m===J?O(a,b.l):v(b,void 0,function(b){return t(a,b)},function(b){return O(a,b)})}function x(a,b,c){b.constructor===a.constructor&&c===l&&b.constructor.resolve===k?u(a,
b):c===P?(O(a,P.error),P.error=null):void 0===c?r(a,b):"function"==typeof c?p(a,b,c):r(a,b)}function t(a,b){if(a===b)O(a,new TypeError("You cannot resolve a promise with itself"));else{var c=typeof b;null===b||"object"!==c&&"function"!==c?r(a,b):x(a,b,n(b))}}function w(a){a.Ja&&a.Ja(a.l);z(a)}function r(b,c){b.m===I&&(b.l=c,b.m=M,0!==b.V.length&&a(z,b))}function O(b,c){b.m===I&&(b.m=J,b.l=c,a(w,b))}function v(b,c,d,e){var f=b.V,g=f.length;b.Ja=null;f[g]=c;f[g+M]=d;f[g+J]=e;0===g&&b.m&&a(z,b)}function z(a){var b=
a.V,c=a.m;if(0!==b.length){for(var d,e,f=a.l,g=0;g<b.length;g+=3)d=b[g],e=b[g+c],d?ga(c,d,e,f):e(f);a.V.length=0}}function H(){this.error=null}function ga(a,b,c,d){var e="function"==typeof c,f=void 0,g=void 0,h=void 0,ga=void 0;if(e){var l;try{l=c(d)}catch(Od){l=(Q.error=Od,Q)}if(f=l,f===Q?(ga=!0,g=f.error,f.error=null):h=!0,b===f)return void O(b,new TypeError("A promises callback cannot return that same promise."))}else f=d,h=!0;b.m!==I||(e&&h?t(b,f):ga?O(b,g):a===M?r(b,f):a===J&&O(b,f))}function Pd(a,
b){try{b(function(b){t(a,b)},function(b){O(a,b)})}catch(Ld){O(a,Ld)}}function Kc(a){a[K]=R++;a.m=void 0;a.l=void 0;a.V=[]}function ba(a,b){this.jb=a;this.H=new a(m);this.H[K]||Kc(this.H);Lc(b)?(this.length=b.length,this.aa=b.length,this.l=Array(this.length),0===this.length?r(this.H,this.l):(this.length=this.length||0,this.ib(b),0===this.aa&&r(this.H,this.l))):O(this.H,Error("Array Methods must be provided an Array"))}function F(a){this[K]=R++;this.l=this.m=void 0;this.V=[];if(m!==a){if("function"!=
typeof a)throw new TypeError("You must pass a resolver function as the first argument to the promise constructor");if(this instanceof F)Pd(this,a);else throw new TypeError("Failed to construct 'Promise': Please use the 'new' operator, this object constructor cannot be called as a function.");}}var fb=void 0,Lc=fb=Array.isArray?Array.isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},aa=0,D=void 0,E=void 0,y=(fb="undefined"!=typeof window?window:void 0)||{},L=y.MutationObserver||
y.WebKitMutationObserver,y="undefined"!=typeof Uint8ClampedArray&&"undefined"!=typeof importScripts&&"undefined"!=typeof MessageChannel,C=Array(1E3),N=void 0,N="undefined"==typeof self&&"undefined"!=typeof process&&"[object process]"==={}.toString.call(process)?b():L?d():y?e():fb||"function"!=typeof require?f():h(),K=Math.random().toString(36).substring(16),I=void 0,M=1,J=2,P=new H,Q=new H,R=0;return ba.prototype.ib=function(a){for(var b=0;this.m===I&&b<a.length;b++)this.hb(a[b],b)},ba.prototype.hb=
function(a,b){var c=this.jb,d=c.resolve;d===k?(d=n(a),d===l&&a.m!==I?this.ua(a.m,b,a.l):"function"!=typeof d?(this.aa--,this.l[b]=a):c===F?(c=new c(m),x(c,a,d),this.va(c,b)):this.va(new c(function(b){return b(a)}),b)):this.va(d(a),b)},ba.prototype.ua=function(a,b,c){var d=this.H;d.m===I&&(this.aa--,a===J?O(d,c):this.l[b]=c);0===this.aa&&r(d,this.l)},ba.prototype.va=function(a,b){var c=this;v(a,void 0,function(a){return c.ua(M,b,a)},function(a){return c.ua(J,b,a)})},F.g=function(a){return(new ba(this,
a)).H},F.h=function(a){var b=this;return new b(Lc(a)?function(c,d){for(var e=a.length,f=0;f<e;f++)b.resolve(a[f]).then(c,d)}:function(a,b){return b(new TypeError("You must pass an array to race."))})},F.resolve=k,F.i=function(a){var b=new this(m);return O(b,a),b},F.f=function(a){E=a},F.c=function(b){a=b},F.b=a,F.prototype={constructor:F,then:l,"catch":function(a){return this.then(null,a)}},F.a=function(){var a=void 0;if("undefined"!=typeof global)a=global;else if("undefined"!=typeof self)a=self;else try{a=
Function("return this")()}catch(Md){throw Error("polyfill failed because global object is unavailable in this environment");}var b=a.Promise;if(b){var c=null;try{c=Object.prototype.toString.call(b.resolve())}catch(Md){}if("[object Promise]"===c&&!b.Ib)return}a.Promise=F},F.Promise=F,F.a(),F});(function(a){function b(a,b){if("function"===typeof window.CustomEvent)return new CustomEvent(a,b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}
function c(a){if(k)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!h(b)&&(b=b.parentNode););a.__importDoc=b}return b}function d(a){var b=document.querySelectorAll("link[rel=import]:not(import-dependency)"),c=b.length;if(c)for(var d=0,e=b.length,f;d<e&&(f=b[d]);d++)g(f,function(){--c||a()});else a()}function e(a){function b(){"loading"!==document.readyState&&document.body&&
(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function f(a){e(function(){return d(function(){return a&&a()})})}function g(a,b){if(a.__loaded)b&&b();else if("script"!==a.localName||a.src){var c=function(d){a.removeEventListener(d.type,c);a.__loaded=!0;b&&b()};a.addEventListener("load",c);u&&"style"===a.localName||a.addEventListener("error",c)}else a.__loaded=!0,b&&b()}function h(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&
"import"===a.rel}function l(){var a=this;this.a={};this.b=0;this.f=new MutationObserver(function(b){return a.o(b)});this.f.observe(document.head,{childList:!0,subtree:!0});this.c(document)}var k="import"in document.createElement("link"),m=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return m||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var n=/(^\/)|(^#)|(^[\w-\d]*:)/,q=/(url\()([^)]*)(\))/g,
r=/(@import[\s]+(?!url\())([^;]*)(;)/g,t=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,p={qb:function(a,b){a.href&&a.setAttribute("href",p.Ca(a.getAttribute("href"),b));a.src&&a.setAttribute("src",p.Ca(a.getAttribute("src"),b));if("style"===a.localName){var c=p.Ta(a.textContent,b,q);a.textContent=p.Ta(c,b,r)}},Ta:function(a,b,c){return a.replace(c,function(a,c,d,e){a=d.replace(/["']/g,"");b&&(a=p.Ua(a,b));return c+"'"+a+"'"+e})},Ca:function(a,b){return a&&n.test(a)?a:p.Ua(a,b)},Ua:function(a,
b){if(void 0===p.qa){p.qa=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";p.qa="http://a/c%20d"===c.href}catch(ba){}}if(p.qa)return(new URL(a,b)).href;c=p.fb;c||(c=document.implementation.createHTMLDocument("temp"),p.fb=c,c.Fa=c.createElement("base"),c.head.appendChild(c.Fa),c.Ea=c.createElement("a"));c.Fa.href=b;c.Ea.href=a;return c.Ea.href||a}},x={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){a=a.split(",");var d=a[1],d=-1<a[0].indexOf(";base64")?atob(d):decodeURIComponent(d);
b(d)}else{var e=new XMLHttpRequest;e.open("GET",a,x.async);e.onload=function(){var a=e.getResponseHeader("Location");a&&!a.indexOf("/")&&(a=(location.origin||location.protocol+"//"+location.host)+a);var d=e.response||e.responseText;304===e.status||!e.status||200<=e.status&&300>e.status?b(d,a):c(d)};e.send()}else c("error: href must be specified")}},u=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);l.prototype.c=function(a){a=a.querySelectorAll("link[rel=import]");for(var b=
0,c=a.length;b<c;b++)this.h(a[b])};l.prototype.h=function(a){var b=this,c=a.href;if(void 0!==this.a[c]){var d=this.a[c];d&&d.__loaded&&(a.import=d,this.g(a))}else this.b++,this.a[c]="pending",x.load(c,function(a,d){a=b.s(a,d||c);b.a[c]=a;b.b--;b.c(a);b.i()},function(){b.a[c]=null;b.b--;b.i()})};l.prototype.s=function(a,b){if(!a)return document.createDocumentFragment();u&&(a=a.replace(t,function(a,b,c){return-1===a.indexOf("type=")?b+" type=import-disable "+c:a}));var c=document.createElement("template");
c.innerHTML=a;if(c.content)a=c.content;else for(a=document.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);if(c=a.querySelector("base"))b=p.Ca(c.getAttribute("href"),b),c.removeAttribute("href");for(var c=a.querySelectorAll('link[rel=import], link[rel=stylesheet][href][type=import-disable],\n    style:not([type]), link[rel=stylesheet][href]:not([type]),\n    script:not([type]), script[type="application/javascript"],\n    script[type="text/javascript"]'),d=0,e=0,f=c.length,h;e<f&&
(h=c[e]);e++)g(h),p.qb(h,b),h.setAttribute("import-dependency",""),"script"===h.localName&&!h.src&&h.textContent&&(h.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(h.textContent+("\n//# sourceURL="+b+(d?"-"+d:"")+".js\n"))),h.textContent="",d++);return a};l.prototype.i=function(){var a=this;if(!this.b){this.f.disconnect();this.flatten(document);var b=!1,c=!1,d=function(){c&&b&&(a.c(document),a.b||(a.f.observe(document.head,{childList:!0,subtree:!0}),a.j()))};this.A(function(){c=
!0;d()});this.u(function(){b=!0;d()})}};l.prototype.flatten=function(a){a=a.querySelectorAll("link[rel=import]");for(var b=0,c=a.length,d;b<c&&(d=a[b]);b++){var e=this.a[d.href];(d.import=e)&&e.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(this.a[d.href]=d,d.readyState="loading",d.import=d,this.flatten(e),d.appendChild(e))}};l.prototype.u=function(a){function b(e){if(e<d){var f=c[e],h=document.createElement("script");f.removeAttribute("import-dependency");for(var l=0,k=f.attributes.length;l<k;l++)h.setAttribute(f.attributes[l].name,
f.attributes[l].value);m=h;f.parentNode.replaceChild(h,f);g(h,function(){m=null;b(e+1)})}else a()}var c=document.querySelectorAll("script[import-dependency]"),d=c.length;b(0)};l.prototype.A=function(a){var b=document.querySelectorAll("style[import-dependency],\n    link[rel=stylesheet][import-dependency]"),d=b.length;if(d)for(var e=u&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]"),f={},h=0,l=b.length;h<l&&(f.w=b[h]);f={w:f.w},h++){if(g(f.w,function(b){return function(){b.w.removeAttribute("import-dependency");
--d||a()}}(f)),e&&f.w.parentNode!==document.head){var k=document.createElement(f.w.localName);k.__appliedElement=f.w;k.setAttribute("type","import-placeholder");f.w.parentNode.insertBefore(k,f.w.nextSibling);for(k=c(f.w);k&&c(k);)k=c(k);k.parentNode!==document.head&&(k=null);document.head.insertBefore(f.w,k);f.w.removeAttribute("type")}}else a()};l.prototype.j=function(){for(var a=document.querySelectorAll("link[rel=import]"),b=a.length-1,c;0<=b&&(c=a[b]);b--)this.g(c)};l.prototype.g=function(a){a.__loaded||
(a.__loaded=!0,a.import&&(a.import.readyState="complete"),a.dispatchEvent(b(a.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};l.prototype.o=function(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.addedNodes)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];e&&e.nodeType===Node.ELEMENT_NODE&&(h(e)?this.h(e):this.c(e))}}};if(k){for(var v=document.querySelectorAll("link[rel=import]"),z=0,C=v.length,y;z<C&&(y=v[z]);z++)y.import&&"loading"===y.import.readyState||(y.__loaded=
!0);v=function(a){a=a.target;h(a)&&(a.__loaded=!0)};document.addEventListener("load",v,!0);document.addEventListener("error",v,!0)}else{var w=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!w||w.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=h(this)?this:c(this);return a?a.href:w&&w.get?w.get.call(this):(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});e(function(){return new l})}f(function(){return document.dispatchEvent(b("HTMLImportsLoaded",
{cancelable:!0,bubbles:!0,detail:void 0}))});a.useNative=k;a.whenReady=f;a.importForElement=c})(window.HTMLImports=window.HTMLImports||{});(function(){window.WebComponents=window.WebComponents||{flags:{}};var a=document.querySelector('script[src*="webcomponents-lite.js"]'),b=/wc-(.+)/,c={};if(!c.noOpts){location.search.slice(1).split("&").forEach(function(a){a=a.split("=");var d;a[0]&&(d=a[0].match(b))&&(c[d[1]]=a[1]||!0)});if(a)for(var d=0,e;e=a.attributes[d];d++)"src"!==e.name&&(c[e.name]=e.value||
!0);c.log&&c.log.split?(a=c.log.split(","),c.log={},a.forEach(function(a){c.log[a]=!0})):c.log={}}window.WebComponents.flags=c;if(a=c.shadydom)window.ShadyDOM=window.ShadyDOM||{},window.ShadyDOM.force=a;(a=c.register||c.ce)&&window.customElements&&(window.customElements.forcePolyfill=a)})();var y=window.ShadyDOM||{};y.sb=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var gb=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");y.W=!!(gb&&gb.configurable&&gb.get);y.Oa=y.force||
!y.sb;var ca=Element.prototype,Mc=ca.matches||ca.matchesSelector||ca.mozMatchesSelector||ca.msMatchesSelector||ca.oMatchesSelector||ca.webkitMatchesSelector,Na=document.createTextNode(""),Lb=0,Ma=[];(new MutationObserver(function(){for(;Ma.length;)try{Ma.shift()()}catch(a){throw Na.textContent=Lb++,a;}})).observe(Na,{characterData:!0});var ea=[],Oa;na.list=ea;ma.prototype.zb=function(){var a=this;this.a||(this.a=!0,Kb(function(){a.b()}))};ma.prototype.b=function(){if(this.a){this.a=!1;var a=this.takeRecords();
a.length&&this.da.forEach(function(b){b(a)})}};ma.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};var ic=Element.prototype.appendChild,Va=Element.prototype.insertBefore,X=Element.prototype.removeChild,Nc=Element.prototype.setAttribute,Oc=Element.prototype.removeAttribute,hb=Element.prototype.cloneNode,Wa=Document.prototype.importNode,
qc=Element.prototype.addEventListener,tc=Element.prototype.removeEventListener,pc=Window.prototype.addEventListener,sc=Window.prototype.removeEventListener,ib=Element.prototype.dispatchEvent,Qd=Object.freeze({appendChild:ic,insertBefore:Va,removeChild:X,setAttribute:Nc,removeAttribute:Oc,cloneNode:hb,importNode:Wa,addEventListener:qc,removeEventListener:tc,Nb:pc,Ob:sc,dispatchEvent:ib}),sd=/[&\u00A0"]/g,vd=/[&\u00A0<>]/g,td=Ob("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),
ud=Ob("style script xmp iframe noembed noframes plaintext noscript".split(" ")),D=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),E=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1),Rd=Object.freeze({parentNode:R,firstChild:Ia,lastChild:Ja,previousSibling:Pb,nextSibling:Qb,childNodes:da,parentElement:Rb,firstElementChild:Sb,lastElementChild:Tb,previousElementSibling:Ub,nextElementSibling:Vb,children:Wb,innerHTML:Xb,textContent:Yb}),jb=Object.getOwnPropertyDescriptor(Element.prototype,
"innerHTML")||Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML"),ta=document.implementation.createHTMLDocument("inert").createElement("div"),kb=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),Zb={parentElement:{get:function(){var a=this.__shady&&this.__shady.parentNode;a&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:Rb(this)},configurable:!0},parentNode:{get:function(){var a=this.__shady&&this.__shady.parentNode;return void 0!==a?a:R(this)},configurable:!0},
nextSibling:{get:function(){var a=this.__shady&&this.__shady.nextSibling;return void 0!==a?a:Qb(this)},configurable:!0},previousSibling:{get:function(){var a=this.__shady&&this.__shady.previousSibling;return void 0!==a?a:Pb(this)},configurable:!0},className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0},nextElementSibling:{get:function(){if(this.__shady&&void 0!==this.__shady.nextSibling){for(var a=this.nextSibling;a&&a.nodeType!==
Node.ELEMENT_NODE;)a=a.nextSibling;return a}return Vb(this)},configurable:!0},previousElementSibling:{get:function(){if(this.__shady&&void 0!==this.__shady.previousSibling){for(var a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return Ub(this)},configurable:!0}},Qa={childNodes:{get:function(){var a;if(this.__shady&&void 0!==this.__shady.firstChild){if(!this.__shady.childNodes){this.__shady.childNodes=[];for(var b=this.firstChild;b;b=b.nextSibling)this.__shady.childNodes.push(b)}a=
this.__shady.childNodes}else a=da(this);a.item=function(b){return a[b]};return a},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=this.__shady&&this.__shady.firstChild;return void 0!==a?a:Ia(this)},configurable:!0},lastChild:{get:function(){var a=this.__shady&&this.__shady.lastChild;return void 0!==a?a:Ja(this)},configurable:!0},textContent:{get:function(){if(this.__shady&&void 0!==this.__shady.firstChild){for(var a=
[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&a.push(d.textContent);return a.join("")}return Yb(this)},set:function(a){if(this.nodeType!==Node.ELEMENT_NODE)this.nodeValue=a;else{for(;this.firstChild;)this.removeChild(this.firstChild);this.appendChild(document.createTextNode(a))}},configurable:!0},firstElementChild:{get:function(){if(this.__shady&&void 0!==this.__shady.firstChild){for(var a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return Sb(this)},
configurable:!0},lastElementChild:{get:function(){if(this.__shady&&void 0!==this.__shady.lastChild){for(var a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return Tb(this)},configurable:!0},children:{get:function(){var a;this.__shady&&void 0!==this.__shady.firstChild?a=Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE}):a=Wb(this);a.item=function(b){return a[b]};return a},configurable:!0},innerHTML:{get:function(){var a=
"template"===this.localName?this.content:this;return this.__shady&&void 0!==this.__shady.firstChild?Pa(a):Xb(a)},set:function(a){for(var b="template"===this.localName?this.content:this;b.firstChild;)b.removeChild(b.firstChild);for(jb&&jb.set?jb.set.call(ta,a):ta.innerHTML=a;ta.firstChild;)b.appendChild(ta.firstChild)},configurable:!0}},Pc={shadowRoot:{get:function(){return this.__shady&&this.__shady.root||null},set:function(a){this.__shady=this.__shady||{};this.__shady.root=a},configurable:!0}},Ra=
{activeElement:{get:function(){var a;a=kb&&kb.get?kb.get.call(document):y.W?void 0:document.activeElement;if(a&&a.nodeType){var b=!!C(this);if(this===document||b&&this.host!==a&&this.host.contains(a)){for(b=W(a);b&&b!==this;)a=b.host,b=W(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},configurable:!0}},Jb=y.W?function(){}:function(a){a.__shady&&a.__shady.eb||(a.__shady=a.__shady||{},a.__shady.eb=!0,M(a,Zb,!0))},Ib=y.W?function(){}:function(a){a.__shady&&
a.__shady.bb||(a.__shady=a.__shady||{},a.__shady.bb=!0,M(a,Qa,!0),M(a,Pc,!0))},ua=null,Sd={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,
pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},uc={get composed(){!1!==this.isTrusted&&void 0===this.na&&(this.na=Sd[this.type]);return this.na||!1},composedPath:function(){this.Ga||(this.Ga=Xa(this.__target,this.composed));return this.Ga},get target(){return kc(this.currentTarget,this.composedPath())},get relatedTarget(){if(!this.Ha)return null;this.Ia||
(this.Ia=Xa(this.Ha,!0));return kc(this.currentTarget,this.Ia)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.oa=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.oa=this.ab=!0}},Za={focus:!0,blur:!0},Td=Ya(window.Event),Ud=Ya(window.CustomEvent),Vd=Ya(window.MouseEvent),Wd="function"===typeof Event?Event:function(a,b){b=b||{};var c=document.createEvent("Event");c.initEvent(a,!!b.bubbles,!!b.cancelable);return c};H.prototype.rb=
function(){return this.root.querySelectorAll("slot")};H.prototype.za=function(a){return a.localName&&"slot"==a.localName};H.prototype.wa=function(){return this.root.ya()?this.g(this.c()):[]};H.prototype.c=function(){for(var a=[],b=0,c=this.root.host.firstChild;c;c=c.nextSibling)a[b++]=c;return a};H.prototype.g=function(a){for(var b=[],c=this.root.sa(),d=0,e=c.length,f;d<e&&(f=c[d]);d++){this.f(f,a);var g=f.parentNode;(g=g&&g.__shady&&g.__shady.root)&&g.ya()&&b.push(g)}for(c=0;c<a.length;c++)if(d=
a[c])d.__shady=d.__shady||{},d.__shady.assignedSlot=void 0,(e=R(d))&&X.call(e,d);return b};H.prototype.f=function(a,b){var c=a.__shady.assignedNodes;c&&this.Ka(a,!0);a.__shady.assignedNodes=[];for(var d=!1,e=!1,f=0,g=b.length,h;f<g;f++)(h=b[f])&&this.h(h,a)&&(h.__shady.ta!=a&&(d=!0),this.b(h,a),b[f]=void 0,e=!0);if(!e)for(b=a.childNodes,e=0;e<b.length;e++)h=b[e],h.__shady.ta!=a&&(d=!0),this.b(h,a);if(c){for(h=0;h<c.length;h++)c[h].__shady.ta=null;a.__shady.assignedNodes.length<c.length&&(d=!0)}this.i(a);
d&&this.a(a)};H.prototype.Ka=function(a,b){var c=a.__shady.assignedNodes;if(c)for(var d=0;d<c.length;d++){var e=c[d];b&&(e.__shady.ta=e.__shady.assignedSlot);e.__shady.assignedSlot===a&&(e.__shady.assignedSlot=null)}};H.prototype.h=function(a,b){b=(b=b.getAttribute("name"))?b.trim():"";a=(a=a.getAttribute&&a.getAttribute("slot"))?a.trim():"";return a==b};H.prototype.b=function(a,b){b.__shady.assignedNodes.push(a);a.__shady.assignedSlot=b};H.prototype.i=function(a){var b=a.__shady.assignedNodes;a.__shady.O=
[];for(var c=0,d;c<b.length&&(d=b[c]);c++)if(this.za(d)){var e=d.__shady.O;if(e)for(var f=0;f<e.length;f++)a.__shady.O.push(e[f])}else a.__shady.O.push(b[c])};H.prototype.a=function(a){ib.call(a,new Wd("slotchange"));a.__shady.assignedSlot&&this.a(a.__shady.assignedSlot)};H.prototype.fa=function(a){return!a.__shady.assignedSlot};var Hb={};q.prototype=Object.create(DocumentFragment.prototype);q.prototype.i=function(a){this.cb="ShadyRoot";V(a);V(this);a.shadowRoot=this;this.host=a;this.ra=this.M=!1;
this.B=new H(this);this.update()};q.prototype.update=function(){var a=this;this.M||(this.M=!0,Mb(function(){return a.Sa()}))};q.prototype.h=function(){for(var a=this,b=this;b;)b.M&&(a=b),b=b.lb();return a};q.prototype.lb=function(){var a=this.host.getRootNode();if(C(a))for(var b=this.host.childNodes,c=0,d;c<b.length;c++)if(d=b[c],this.B.za(d))return a};q.prototype.Sa=function(){this.M&&this.h()._render()};q.prototype._render=function(){this.ra=this.M=!1;this.ba||this.f();this.ba=!1;this.wa();this.j()};
q.prototype.wa=function(){for(var a=this.B.wa(),b=0;b<a.length;b++)a[b]._render()};q.prototype.f=function(){var a=this.a;if(a)for(var b=0,c;b<a.length;b++)c=a[b],c.getRootNode()!==this&&this.B.Ka(c);a=this.a=this.B.rb();for(b=0;b<a.length;b++)c=a[b],c.__shady=c.__shady||{},V(c),V(c.parentNode)};q.prototype.j=function(){this.g()};q.prototype.g=function(){this.c(this.host,this.b(this.host));for(var a=this.sa(),b=0,c=a.length,d,e;b<c&&(d=a[b]);b++)e=d.parentNode,e!==this.host&&e!==this&&this.c(e,this.b(e))};
q.prototype.b=function(a){var b=[];a=(a.__shady&&a.__shady.root||a).childNodes;for(var c=0;c<a.length;c++){var d=a[c];if(this.B.za(d))for(var e=d.__shady.O||(d.__shady.O=[]),f=0;f<e.length;f++){var g=e[f];this.fa(d,g)&&b.push(g)}else b.push(d)}return b};q.prototype.fa=function(a,b){return this.B.fa(a,b)};q.prototype.c=function(a,b){for(var c=da(a),d=yd(b,b.length,c,c.length),e=0,f=0,g;e<d.length&&(g=d[e]);e++){for(var h=0,k;h<g.Y.length&&(k=g.Y[h]);h++)R(k)===a&&X.call(a,k),c.splice(g.index+f,1);
f-=g.ca}for(e=0;e<d.length&&(g=d[e]);e++)for(f=c[g.index],h=g.index;h<g.index+g.ca;h++)k=b[h],Va.call(a,k,f),c.splice(h,0,k)};q.prototype.ya=function(){return!(!this.a||!this.a.length)};q.prototype.sa=function(){this.a||this.f();return this.a};q.prototype.addEventListener=function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.pa=this;this.host.addEventListener(a,b,c)};q.prototype.removeEventListener=function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.pa=this;this.host.removeEventListener(a,
b,c)};q.prototype.getElementById=function(a){return pa(this,function(b){return b.id==a},function(a){return!!a})[0]||null};(function(a){M(a,Qa,!0);M(a,Ra,!0)})(q.prototype);var Cd={addEventListener:nc.bind(window),removeEventListener:rc.bind(window)},Bd={addEventListener:nc,removeEventListener:rc,appendChild:function(a){return hc(this,a)},insertBefore:function(a,b){return hc(this,a,b)},removeChild:function(a){if(a.parentNode!==this)throw Error("The node to be removed is not a child of this node: "+
a);if(!ac(a)){var b=C(this)?this.host:this,c=R(a);b===c&&X.call(b,a)}Ta(this,null,a);return a},replaceChild:function(a,b){this.insertBefore(a,b);this.removeChild(b);return a},cloneNode:function(a){var b;if("template"==this.localName)b=hb.call(this,a);else if(b=hb.call(this,!1),a){a=this.childNodes;for(var c=0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return Ua(this)},get isConnected(){var a=this.ownerDocument;if(a&&a.contains&&a.contains(this)||(a=a.documentElement)&&
a.contains&&a.contains(this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(a instanceof q?a.host:void 0);return!!(a&&a instanceof Document)},dispatchEvent:function(a){na();return ib.call(this,a)}},Dd={get assignedSlot(){return vc(this)}},$a={querySelector:function(a){return pa(this,function(b){return Mc.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a){return pa(this,function(b){return Mc.call(b,a)})}},yc={assignedNodes:function(a){if("slot"===this.localName)return gc(this),
this.__shady?(a&&a.flatten?this.__shady.O:this.__shady.assignedNodes)||[]:[]}},wc=La({setAttribute:function(a,b){ua||(ua=window.ShadyCSS&&window.ShadyCSS.ScopingShim);ua&&"class"===a?ua.setElementClass(this,b):(Nc.call(this,a,b),ec(this,a))},removeAttribute:function(a){Oc.call(this,a);ec(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";if(!a)throw"Not enough arguments.";return new q(Hb,this)},get slot(){return this.getAttribute("slot")},set slot(a){this.setAttribute("slot",a)},
get assignedSlot(){return vc(this)}},$a,yc);Object.defineProperties(wc,Pc);var xc=La({importNode:function(a,b){return jc(a,b)},getElementById:function(a){return pa(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},$a);Object.defineProperties(xc,{_activeElement:Ra.activeElement});var Xd=HTMLElement.prototype.blur,Ed=La({blur:function(){var a=this.shadowRoot;(a=a&&a.activeElement)?a.blur():Xd.call(this)}});y.Oa&&(window.ShadyDOM={inUse:y.Oa,patch:function(a){return a},isShadyRoot:C,
enqueue:Mb,flush:na,settings:y,filterMutations:rd,observeChildren:pd,unobserveChildren:od,nativeMethods:Qd,nativeTree:Rd},window.Event=Td,window.CustomEvent=Ud,window.MouseEvent=Vd,xd(),Ad(),window.ShadowRoot=q);var Fd=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));z.prototype.K=function(a,b){this.s.set(a,b);this.o.set(b.constructor,b)};z.prototype.f=function(a){return this.s.get(a)};z.prototype.J=function(a){return this.o.get(a)};
z.prototype.u=function(a){this.h=!0;this.i.push(a)};z.prototype.j=function(a){var b=this;this.h&&Q(a,function(a){return b.g(a)})};z.prototype.g=function(a){if(this.h&&!a.__CE_patched){a.__CE_patched=!0;for(var b=0;b<this.i.length;b++)this.i[b](a)}};z.prototype.b=function(a){var b=[];Q(a,function(a){return b.push(a)});for(a=0;a<b.length;a++){var c=b[a];1===c.__CE_state?this.connectedCallback(c):this.A(c)}};z.prototype.a=function(a){var b=[];Q(a,function(a){return b.push(a)});for(a=0;a<b.length;a++){var c=
b[a];1===c.__CE_state&&this.disconnectedCallback(c)}};z.prototype.c=function(a,b){b=b?b:new Set;var c=this,d=[];Q(a,function(a){if("link"===a.localName&&"import"===a.getAttribute("rel")){var e=a.import;e instanceof Node&&"complete"===e.readyState?(e.__CE_isImportDocument=!0,e.__CE_hasRegistry=!0):a.addEventListener("load",function(){var d=a.import;d.__CE_documentLoadHandled||(d.__CE_documentLoadHandled=!0,d.__CE_isImportDocument=!0,d.__CE_hasRegistry=!0,b.delete(d),c.c(d,b))})}else d.push(a)},b);
if(this.h)for(a=0;a<d.length;a++)this.g(d[a]);for(a=0;a<d.length;a++)this.A(d[a])};z.prototype.A=function(a){if(void 0===a.__CE_state){var b=this.f(a.localName);if(b){b.constructionStack.push(a);var c=b.constructor;try{try{if(new c!==a)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{b.constructionStack.pop()}}catch(f){throw a.__CE_state=2,f;}a.__CE_state=1;a.__CE_definition=b;if(b.attributeChangedCallback)for(b=b.observedAttributes,c=0;c<b.length;c++){var d=
b[c],e=a.getAttribute(d);null!==e&&this.attributeChangedCallback(a,d,null,e,null)}m(a)&&this.connectedCallback(a)}}};z.prototype.connectedCallback=function(a){var b=a.__CE_definition;b.connectedCallback&&b.connectedCallback.call(a)};z.prototype.disconnectedCallback=function(a){var b=a.__CE_definition;b.disconnectedCallback&&b.disconnectedCallback.call(a)};z.prototype.attributeChangedCallback=function(a,b,c,d,e){var f=a.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(b)&&
f.attributeChangedCallback.call(a,b,c,d,e)};Ha.prototype.c=function(){this.L&&this.L.disconnect()};Ha.prototype.f=function(a){var b=this.a.readyState;"interactive"!==b&&"complete"!==b||this.c();for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,d=0;d<c.length;d++)this.b.c(c[d])};Gb.prototype.resolve=function(a){if(this.a)throw Error("Already resolved.");this.a=a;this.b&&this.b(a)};r.prototype.define=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");
if(!zc(a))throw new SyntaxError("The element name '"+a+"' is not valid.");if(this.a.f(a))throw Error("A custom element with name '"+a+"' has already been defined.");if(this.f)throw Error("A custom element is already being defined.");this.f=!0;var d,e,f,g,h;try{var k=function(a){var b=m[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");return b},m=b.prototype;if(!(m instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");
d=k("connectedCallback");e=k("disconnectedCallback");f=k("adoptedCallback");g=k("attributeChangedCallback");h=b.observedAttributes||[]}catch(A){return}finally{this.f=!1}this.a.K(a,{localName:a,constructor:b,connectedCallback:d,disconnectedCallback:e,adoptedCallback:f,attributeChangedCallback:g,observedAttributes:h,constructionStack:[]});this.c.push(a);this.b||(this.b=!0,this.g(function(){return c.j()}))};r.prototype.j=function(){if(!1!==this.b)for(this.b=!1,this.a.c(document);0<this.c.length;){var a=
this.c.shift();(a=this.h.get(a))&&a.resolve(void 0)}};r.prototype.get=function(a){if(a=this.a.f(a))return a.constructor};r.prototype.whenDefined=function(a){if(!zc(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));var b=this.h.get(a);if(b)return b.c;b=new Gb;this.h.set(a,b);this.a.f(a)&&-1===this.c.indexOf(a)&&b.resolve(void 0);return b.c};r.prototype.o=function(a){this.i.c();var b=this.g;this.g=function(c){return a(function(){return b(c)})}};window.CustomElementRegistry=
r;r.prototype.define=r.prototype.define;r.prototype.get=r.prototype.get;r.prototype.whenDefined=r.prototype.whenDefined;r.prototype.polyfillWrapFlushCallback=r.prototype.o;var Da=window.Document.prototype.createElement,jd=window.Document.prototype.createElementNS,id=window.Document.prototype.importNode,kd=window.Document.prototype.prepend,ld=window.Document.prototype.append,vb=window.Node.prototype.cloneNode,ka=window.Node.prototype.appendChild,Db=window.Node.prototype.insertBefore,Ea=window.Node.prototype.removeChild,
Eb=window.Node.prototype.replaceChild,Ga=Object.getOwnPropertyDescriptor(window.Node.prototype,"textContent"),ub=window.Element.prototype.attachShadow,Ba=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),Fa=window.Element.prototype.getAttribute,wb=window.Element.prototype.setAttribute,yb=window.Element.prototype.removeAttribute,la=window.Element.prototype.getAttributeNS,xb=window.Element.prototype.setAttributeNS,zb=window.Element.prototype.removeAttributeNS,Bb=window.Element.prototype.insertAdjacentElement,
$c=window.Element.prototype.prepend,ad=window.Element.prototype.append,cd=window.Element.prototype.before,dd=window.Element.prototype.after,ed=window.Element.prototype.replaceWith,fd=window.Element.prototype.remove,nd=window.HTMLElement,Ca=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),Ab=window.HTMLElement.prototype.insertAdjacentElement,Fb=new function(){},va=window.customElements;if(!va||va.forcePolyfill||"function"!=typeof va.define||"function"!=typeof va.get){var ha=
new z;md(ha);hd(ha);gd(ha);Zc(ha);document.__CE_hasRegistry=!0;var Yd=new r(ha);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:Yd})}var I={STYLE_RULE:1,ma:7,MEDIA_RULE:4,Da:1E3},N={pb:/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,port:/@import[^;]*;/gim,La:/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,Pa:/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,wb:/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,Bb:/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,vb:/^@[^\s]*keyframes/,
Qa:/\s+/g},t=!(window.ShadyDOM&&window.ShadyDOM.inUse),w;window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?w=window.ShadyCSS.nativeCss:window.ShadyCSS?(Cc(window.ShadyCSS),window.ShadyCSS=void 0):Cc(window.WebComponents&&window.WebComponents.flags);var wa=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^\)]*?\)|[^};{])+)|\{([^\}]*)\}(?:(?=[;\s}])|$))/gi,xa=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,Zd=/(--[\w-]+)\s*([:,;)]|$)/gi,$d=/(animation\s*:)|(animation-name\s*:)/,Hd=/@media[^(]*(\([^)]*\))/,
ae=/\{[^}]*\}/g,T=null;p.prototype.a=function(a,b,c){a.__styleScoped?a.__styleScoped=null:this.i(a,b||"",c)};p.prototype.i=function(a,b,c){a.nodeType===Node.ELEMENT_NODE&&this.A(a,b,c);if(a="template"===a.localName?(a.content||a.Fb).childNodes:a.children||a.childNodes)for(var d=0;d<a.length;d++)this.i(a[d],b,c)};p.prototype.A=function(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=
a.getAttribute(be);c?d&&(b=d.replace("style-scope","").replace(b,""),ra(a,b)):ra(a,(d?d+" ":"")+"style-scope "+b)}};p.prototype.b=function(a,b,c){var d=a.__cssBuild;t||"shady"===d?b=Y(b,c):(a=U(a),b=this.S(b,a.is,a.Z,c)+"\n\n");return b.trim()};p.prototype.S=function(a,b,c,d){var e=this.f(b,c);b=this.h(b);var f=this;return Y(a,function(a){a.c||(f.U(a,b,e),a.c=!0);d&&d(a,b,e)})};p.prototype.h=function(a){return a?ce+a:""};p.prototype.f=function(a,b){return b?"[is="+a+"]":a};p.prototype.U=function(a,
b,c){this.j(a,this.g,b,c)};p.prototype.j=function(a,b,c,d){a.selector=a.C=this.o(a,b,c,d)};p.prototype.o=function(a,b,c,d){var e=a.selector.split(Qc);if(!Dc(a)){a=0;for(var f=e.length,g;a<f&&(g=e[a]);a++)e[a]=b.call(this,g,c,d)}return e.join(Qc)};p.prototype.g=function(a,b,c){var d=this,e=!1;a=a.trim();a=a.replace(de,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"});a=a.replace(ee,lb+" $1");return a=a.replace(fe,function(a,g,h){e||(a=d.J(h,g,b,c),e=e||a.stop,g=a.ob,h=a.value);return g+h})};
p.prototype.J=function(a,b,c,d){var e=a.indexOf(mb);0<=a.indexOf(lb)?a=this.R(a,d):0!==e&&(a=c?this.s(a,c):a);c=!1;0<=e&&(b="",c=!0);var f;c&&(f=!0,c&&(a=a.replace(ge,function(a,b){return" > "+b})));a=a.replace(he,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,ob:b,stop:f}};p.prototype.s=function(a,b){a=a.split(Rc);a[0]+=b;return a.join(Rc)};p.prototype.R=function(a,b){var c=a.match(Sc);return(c=c&&c[2].trim()||"")?c[0].match(Tc)?a.replace(Sc,function(a,c,f){return b+
f}):c.split(Tc)[0]===b?c:ie:a.replace(lb,b)};p.prototype.T=function(a){a.selector=a.parsedSelector;this.u(a);this.j(a,this.K)};p.prototype.u=function(a){a.selector===je&&(a.selector="html")};p.prototype.K=function(a){return a.match(mb)?this.g(a,Uc):this.s(a.trim(),Uc)};rb.Object.defineProperties(p.prototype,{c:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});var de=/:(nth[-\w]+)\(([^)]+)\)/,Uc=":not(.style-scope)",Qc=",",fe=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=\[])+)/g,Tc=/[[.:#*]/,
lb=":host",je=":root",mb="::slotted",ee=new RegExp("^("+mb+")"),Sc=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,ge=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,he=/(.*):dir\((?:(ltr|rtl))\)/,ce=".",Rc=":",be="class",ie="should_not_match",x=new p;u.get=function(a){return a?a.__styleInfo:null};u.set=function(a,b){return a.__styleInfo=b};u.prototype.c=function(){return this.G};u.prototype._getStyleRules=u.prototype.c;var Vc=function(a){return a.matches||a.matchesSelector||a.mozMatchesSelector||a.msMatchesSelector||
a.oMatchesSelector||a.webkitMatchesSelector}(window.Element.prototype),ke=navigator.userAgent.match("Trident");n.prototype.U=function(a){var b=this,c={},d=[],e=0;Z(a,function(a){b.c(a);a.index=e++;b.T(a.v.cssText,c)},function(a){d.push(a)});a.b=d;a=[];for(var f in c)a.push(f);return a};n.prototype.c=function(a){if(!a.v){var b={},c={};this.b(a,c)&&(b.F=c,a.rules=null);b.cssText=this.S(a);a.v=b}};n.prototype.b=function(a,b){var c=a.v;if(c){if(c.F)return Object.assign(b,c.F),!0}else{for(var c=a.parsedCssText,
d;a=wa.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}};n.prototype.S=function(a){return this.R(a.parsedCssText)};n.prototype.R=function(a){return a.replace(ae,"").replace(wa,"")};n.prototype.T=function(a,b){for(var c;c=Zd.exec(a);){var d=c[1];":"!==c[2]&&(b[d]=!0)}};n.prototype.ja=function(a){for(var b=Object.getOwnPropertyNames(a),c=0,d;c<b.length;c++)d=b[c],a[d]=this.a(a[d],a)};n.prototype.a=function(a,b){if(a)if(0<=a.indexOf(";"))a=this.f(a,b);else{var c=
this;a=Fc(a,function(a,e,f,g){if(!e)return a+g;(e=c.a(b[e],b))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=c.a(b[f]||f,b)||f;return a+(e||"")+g})}return a&&a.trim()||""};n.prototype.f=function(a,b){a=a.split(";");for(var c=0,d,e;c<a.length;c++)if(d=a[c]){xa.lastIndex=0;if(e=xa.exec(d))d=this.a(b[e[1]],b);else if(e=d.indexOf(":"),-1!==e){var f=d.substring(e),f=f.trim(),f=this.a(f,b)||f;d=d.substring(0,e)+f}a[c]=d&&d.lastIndexOf(";")===d.length-1?d.slice(0,-1):d||""}return a.join(";")};
n.prototype.K=function(a,b){var c="";a.v||this.c(a);a.v.cssText&&(c=this.f(a.v.cssText,b));a.cssText=c};n.prototype.J=function(a,b){var c=a.cssText,d=a.cssText;null==a.Na&&(a.Na=$d.test(c));if(a.Na)if(null==a.ga){a.ga=[];for(var e in b)d=b[e],d=d(c),c!==d&&(c=d,a.ga.push(e))}else{for(e=0;e<a.ga.length;++e)d=b[a.ga[e]],c=d(c);d=c}a.cssText=d};n.prototype.ia=function(a,b){var c={},d=this,e=[];Z(a,function(a){a.v||d.c(a);var f=a.C||a.parsedSelector;b&&a.v.F&&f&&Vc.call(b,f)&&(d.b(a,c),a=a.index,f=parseInt(a/
32,10),e[f]=(e[f]||0)|1<<a%32)},null,!0);return{F:c,key:e}};n.prototype.la=function(a,b,c,d){b.v||this.c(b);if(b.v.F){var e=U(a);a=e.is;var e=e.Z,e=a?x.f(a,e):"html",f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));"shadow"===c&&(g=":host > *"===f||"html"===f,h=h&&!g);if(g||h)c=e,h&&(t&&!b.C&&(b.C=x.o(b,x.g,x.h(a),e)),c=b.C||e),d({Ab:c,ub:h,Jb:g})}};n.prototype.ha=function(a,b){var c={},d=
{},e=this,f=b&&b.__cssBuild;Z(b,function(b){e.la(a,b,f,function(f){Vc.call(a.Gb||a,f.Ab)&&(f.ub?e.b(b,c):e.b(b,d))})},null,!0);return{yb:d,tb:c}};n.prototype.ka=function(a,b,c){var d=this,e=U(a),f=x.f(e.is,e.Z),g=new RegExp("(?:^|[^.#[:])"+(a.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),e=u.get(a).G,h=this.h(e,c);return x.b(a,e,function(a){d.K(a,b);t||Dc(a)||!a.cssText||(d.J(a,h),d.o(a,g,f,c))})};n.prototype.h=function(a,b){a=a.b;var c={};if(!t&&a)for(var d=0,e=a[d];d<a.length;e=a[++d])this.j(e,
b),c[e.keyframesName]=this.i(e);return c};n.prototype.i=function(a){return function(b){return b.replace(a.f,a.a)}};n.prototype.j=function(a,b){a.f=new RegExp(a.keyframesName,"g");a.a=a.keyframesName+"-"+b;a.C=a.C||a.selector;a.selector=a.C.replace(a.keyframesName,a.a)};n.prototype.o=function(a,b,c,d){a.C=a.C||a.selector;d="."+d;for(var e=a.C.split(","),f=0,g=e.length,h;f<g&&(h=e[f]);f++)e[f]=h.match(b)?h.replace(c,d):d+" "+h;a.selector=e.join(",")};n.prototype.u=function(a,b,c){var d=a.getAttribute("class")||
"",e=d;c&&(e=d.replace(new RegExp("\\s*x-scope\\s*"+c+"\\s*","g")," "));e+=(e?" ":"")+"x-scope "+b;d!==e&&ra(a,e)};n.prototype.A=function(a,b,c,d){b=d?d.textContent||"":this.ka(a,b,c);var e=u.get(a),f=e.a;f&&!t&&f!==d&&(f._useCount--,0>=f._useCount&&f.parentNode&&f.parentNode.removeChild(f));t?e.a?(e.a.textContent=b,d=e.a):b&&(d=cb(b,c,a.shadowRoot,e.b)):d?d.parentNode||(ke&&-1<b.indexOf("@media")&&(d.textContent=b),Ec(d,null,e.b)):b&&(d=cb(b,c,null,e.b));d&&(d._useCount=d._useCount||0,e.a!=d&&d._useCount++,
e.a=d);return d};n.prototype.s=function(a,b){var c=qa(a),d=this;a.textContent=Y(c,function(a){var c=a.cssText=a.parsedCssText;a.v&&a.v.cssText&&(c=c.replace(N.La,"").replace(N.Pa,""),a.cssText=d.f(c,b))})};rb.Object.defineProperties(n.prototype,{g:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var P=new n,nb={},ya=window.customElements;if(ya&&!t){var le=ya.define;ya.define=function(a,b,c){var d=document.createComment(" Shady DOM styles for "+a+" "),e=document.head;e.insertBefore(d,
(T?T.nextSibling:null)||e.firstChild);T=d;nb[a]=d;return le.call(ya,a,b,c)}}ja.prototype.a=function(a,b,c){for(var d=0;d<c.length;d++){var e=c[d];if(a.F[e]!==b[e])return!1}return!0};ja.prototype.b=function(a,b,c,d){var e=this.cache[a]||[];e.push({F:b,styleElement:c,D:d});e.length>this.c&&e.shift();this.cache[a]=e};ja.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d];if(this.a(e,b,c))return e}};if(!t){var Wc=new MutationObserver(Gc),Xc=function(a){Wc.observe(a,
{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Xc(document);else{var ob=function(){Xc(document.body)};window.HTMLImports?window.HTMLImports.whenReady(ob):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){ob();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",a)}else ob()})}tb=function(){Gc(Wc.takeRecords())}}var sa={},Kd=Promise.resolve(),db=null,Ic=window.HTMLImports&&
window.HTMLImports.whenReady||null,eb,za=null,ia=null;L.prototype.Ma=function(){!this.enqueued&&ia&&(this.enqueued=!0,sb(ia))};L.prototype.b=function(a){a.__seenByShadyCSS||(a.__seenByShadyCSS=!0,this.customStyles.push(a),this.Ma())};L.prototype.a=function(a){return a.__shadyCSSCachedStyle?a.__shadyCSSCachedStyle:a.getStyle?a.getStyle():a};L.prototype.c=function(){for(var a=this.customStyles,b=0;b<a.length;b++){var c=a[b];if(!c.__shadyCSSCachedStyle){var d=this.a(c);if(d){var e=d.__appliedElement;
if(e)for(var f=0;f<d.attributes.length;f++){var g=d.attributes[f];e.setAttribute(g.name,g.value)}d=e||d;za&&za(d);c.__shadyCSSCachedStyle=d}}}return a};L.prototype.addCustomStyle=L.prototype.b;L.prototype.getStyleForCustomStyle=L.prototype.a;L.prototype.processStyles=L.prototype.c;Object.defineProperties(L.prototype,{transformCallback:{get:function(){return za},set:function(a){za=a}},validateCallback:{get:function(){return ia},set:function(a){var b=!1;ia||(b=!0);ia=a;b&&this.Ma()}}});var Yc=new ja;
k.prototype.J=function(){tb()};k.prototype.ha=function(a){var b=this.s[a]=(this.s[a]||0)+1;return a+"-"+b};k.prototype.Ya=function(a){return qa(a)};k.prototype.$a=function(a){return Y(a)};k.prototype.U=function(a){a=a.content.querySelectorAll("style");for(var b=[],c=0;c<a.length;c++){var d=a[c];b.push(d.textContent);d.parentNode.removeChild(d)}return b.join("").trim()};k.prototype.ja=function(a){return(a=a.content.querySelector("style"))?a.getAttribute("css-build")||"":""};k.prototype.prepareTemplate=
function(a,b,c){if(!a.f){a.f=!0;a.name=b;a.extends=c;sa[b]=a;var d=this.ja(a),e=this.U(a);c={is:b,extends:c,Db:d};t||x.a(a.content,b);this.c();var f=xa.test(e)||wa.test(e);xa.lastIndex=0;wa.lastIndex=0;e=bb(e);f&&w&&this.a&&this.a.transformRules(e,b);a._styleAst=e;a.g=d;d=[];w||(d=P.U(a._styleAst));if(!d.length||w)b=this.ia(c,a._styleAst,t?a.content:null,nb[b]),a.a=b;a.c=d}};k.prototype.ia=function(a,b,c,d){b=x.b(a,b);if(b.length)return cb(b,a.is,c,d)};k.prototype.la=function(a){var b=U(a),c=b.is,
b=b.Z,d=nb[c],c=sa[c],e,f;c&&(e=c._styleAst,f=c.c);return u.set(a,new u(e,d,f,0,b))};k.prototype.S=function(){!this.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(this.a=window.ShadyCSS.ApplyShim,this.a.invalidCallback=Id)};k.prototype.T=function(){var a=this;!this.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(this.b=window.ShadyCSS.CustomStyleInterface,this.b.transformCallback=function(b){a.A(b)},this.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.i)&&
a.f()})})};k.prototype.c=function(){this.S();this.T()};k.prototype.f=function(){this.c();if(this.b){var a=this.b.processStyles();this.b.enqueued&&(w?this.Wa(a):(this.u(this.g,this.h),this.K(a)),this.b.enqueued=!1,this.i&&!w&&this.styleDocument())}};k.prototype.styleElement=function(a,b){var c=U(a).is,d=u.get(a);d||(d=this.la(a));this.j(a)||(this.i=!0);b&&(d.P=d.P||{},Object.assign(d.P,b));if(w){if(d.P){b=d.P;for(var e in b)null===e?a.style.removeProperty(e):a.style.setProperty(e,b[e])}if(((e=sa[c])||
this.j(a))&&e&&e.a&&!Hc(e)){if(Hc(e)||e._applyShimValidatingVersion!==e._applyShimNextVersion)this.c(),this.a&&this.a.transformRules(e._styleAst,c),e.a.textContent=x.b(a,d.G),Jd(e);t&&(c=a.shadowRoot)&&(c.querySelector("style").textContent=x.b(a,d.G));d.G=e._styleAst}}else this.u(a,d),d.Aa&&d.Aa.length&&this.R(a,d)};k.prototype.o=function(a){return(a=a.getRootNode().host)?u.get(a)?a:this.o(a):this.g};k.prototype.j=function(a){return a===this.g};k.prototype.R=function(a,b){var c=U(a).is,d=Yc.fetch(c,
b.I,b.Aa),e=d?d.styleElement:null,f=b.D;b.D=d&&d.D||this.ha(c);e=P.A(a,b.I,b.D,e);t||P.u(a,b.D,f);d||Yc.b(c,b.I,e,b.D)};k.prototype.u=function(a,b){var c=this.o(a),d=u.get(c),c=Object.create(d.I||null),e=P.ha(a,b.G);a=P.ia(d.G,a).F;Object.assign(c,e.tb,a,e.yb);this.ka(c,b.P);P.ja(c);b.I=c};k.prototype.ka=function(a,b){for(var c in b){var d=b[c];if(d||0===d)a[c]=d}};k.prototype.styleDocument=function(a){this.styleSubtree(this.g,a)};k.prototype.styleSubtree=function(a,b){var c=a.shadowRoot;(c||this.j(a))&&
this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};k.prototype.Wa=function(a){for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);c&&this.Va(c)}};k.prototype.K=function(a){for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);c&&P.s(c,this.h.I)}};k.prototype.A=function(a){var b=this,c=qa(a);Z(c,function(a){t?x.u(a):x.T(a);w&&(b.c(),
b.a&&b.a.transformRule(a))});w?a.textContent=Y(c):this.h.G.rules.push(c)};k.prototype.Va=function(a){if(w&&this.a){var b=qa(a);this.c();this.a.transformRules(b);a.textContent=Y(b)}};k.prototype.getComputedStyleValue=function(a,b){var c;w||(c=(u.get(a)||u.get(this.o(a))).I[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};k.prototype.Za=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d)for(var d=
d.split(/\s/),e=0;e<d.length;e++)if(d[e]===x.c){c=d[e+1];break}}c&&b.push(x.c,c);w||(c=u.get(a))&&c.D&&b.push(P.g,c.D);ra(a,b.join(" "))};k.prototype.Xa=function(a){return u.get(a)};k.prototype.flush=k.prototype.J;k.prototype.prepareTemplate=k.prototype.prepareTemplate;k.prototype.styleElement=k.prototype.styleElement;k.prototype.styleDocument=k.prototype.styleDocument;k.prototype.styleSubtree=k.prototype.styleSubtree;k.prototype.getComputedStyleValue=k.prototype.getComputedStyleValue;k.prototype.setElementClass=
k.prototype.Za;k.prototype._styleInfoForNode=k.prototype.Xa;k.prototype.transformCustomStyleForDocument=k.prototype.A;k.prototype.getStyleAst=k.prototype.Ya;k.prototype.styleAstToString=k.prototype.$a;k.prototype.flushCustomStyles=k.prototype.f;Object.defineProperties(k.prototype,{nativeShadow:{get:function(){return t}},nativeCss:{get:function(){return w}}});var K=new k,pb,qb;window.ShadyCSS&&(pb=window.ShadyCSS.ApplyShim,qb=window.ShadyCSS.CustomStyleInterface);window.ShadyCSS={ScopingShim:K,prepareTemplate:function(a,
b,c){K.f();K.prepareTemplate(a,b,c)},styleSubtree:function(a,b){K.f();K.styleSubtree(a,b)},styleElement:function(a){K.f();K.styleElement(a)},styleDocument:function(a){K.f();K.styleDocument(a)},getComputedStyleValue:function(a,b){return K.getComputedStyleValue(a,b)},nativeCss:w,nativeShadow:t};pb&&(window.ShadyCSS.ApplyShim=pb);qb&&(window.ShadyCSS.CustomStyleInterface=qb);(function(){var a=window.customElements,b=window.HTMLImports;window.WebComponents=window.WebComponents||{};if(a&&a.polyfillWrapFlushCallback){var c,
d=function(){if(c){var a=c;c=null;a();return!0}},e=b.whenReady;a.polyfillWrapFlushCallback(function(a){c=a;e(d)});b.whenReady=function(a){e(function(){d()?b.whenReady(a):a()})}}b.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})})})();(function(){var a=document.createElement("style");a.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";
var b=document.querySelector("head");b.insertBefore(a,b.firstChild)})()})();
}).call(self)

//# sourceMappingURL=webcomponents-lite.js.map
